<!-- 摄像头相关的 xacro 文件 -->
<robot name="my_kinect" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 摄像头属性 -->
    <xacro:property name="kinect_length" value="0.01" /> <!-- 摄像头长度(x) -->
    <xacro:property name="kinect_width" value="0.025" /> <!-- 摄像头宽度(y) -->
    <xacro:property name="kinect_height" value="0.025" /> <!-- 摄像头高度(z) -->
    <xacro:property name="kinect_x" value="0.08" /> <!-- 摄像头安装的x坐标 -->
    <xacro:property name="kinect_y" value="0.0" /> <!-- 摄像头安装的y坐标 -->
    <xacro:property name="kinect_z" value="${base_link_length / 2 + kinect_height / 2}" /> <!-- 摄像头安装的z坐标:底盘高度 / 2 + 摄像头高度 / 2  -->

    <xacro:property name="kinect_m" value="0.01" /> <!-- 摄像头质量 -->

    <!-- 摄像头关节以及link -->
    <link name="kinect">
        <visual>
            <geometry>
                <box size="${kinect_length} ${kinect_width} ${kinect_height}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <box size="${kinect_length} ${kinect_width} ${kinect_height}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:Box_inertial_matrix m="${kinect_m}" l="${kinect_length}" w="${kinect_width}" h="${kinect_height}" />
    </link>

    <joint name="kinect2base_link" type="fixed">
        <parent link="base_link" />
        <child link="kinect" />
        <origin xyz="${kinect_x} ${kinect_y} ${kinect_z}" />
    </joint>
    <gazebo reference="kinect">
        <material>Gazebo/Blue</material>
    </gazebo>
</robot>