// Generated by gencpp from file sean_ros/AddInts.msg
// DO NOT EDIT!


#ifndef SEAN_ROS_MESSAGE_ADDINTS_H
#define SEAN_ROS_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <sean_ros/AddIntsRequest.h>
#include <sean_ros/AddIntsResponse.h>


namespace sean_ros
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace sean_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sean_ros::AddInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::sean_ros::AddInts&) { return value(); }
};

template<>
struct DataType< ::sean_ros::AddInts > {
  static const char* value()
  {
    return "sean_ros/AddInts";
  }

  static const char* value(const ::sean_ros::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::sean_ros::AddIntsRequest> should match
// service_traits::MD5Sum< ::sean_ros::AddInts >
template<>
struct MD5Sum< ::sean_ros::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sean_ros::AddInts >::value();
  }
  static const char* value(const ::sean_ros::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sean_ros::AddIntsRequest> should match
// service_traits::DataType< ::sean_ros::AddInts >
template<>
struct DataType< ::sean_ros::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::sean_ros::AddInts >::value();
  }
  static const char* value(const ::sean_ros::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sean_ros::AddIntsResponse> should match
// service_traits::MD5Sum< ::sean_ros::AddInts >
template<>
struct MD5Sum< ::sean_ros::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sean_ros::AddInts >::value();
  }
  static const char* value(const ::sean_ros::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sean_ros::AddIntsResponse> should match
// service_traits::DataType< ::sean_ros::AddInts >
template<>
struct DataType< ::sean_ros::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::sean_ros::AddInts >::value();
  }
  static const char* value(const ::sean_ros::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEAN_ROS_MESSAGE_ADDINTS_H
