<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_camera">
    <xacro:property name="camera_length" value="0.01"/>
    <xacro:property name="camera_width" value="0.025"/>
    <xacro:property name="camera_height" value="0.025"/>
    <xacro:property name="camera_x" value="0.08"/>
    <xacro:property name="camera_y" value="0.0"/>
    <xacro:property name="camera_z" value="${(camera_length + base_link_length) / 2}"/>

    <link name="camera">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <material name="black" />
        </visual>
    </link>

    <joint name="camera2base_link" type="fixed">
        <parent link="base_link"/>
        <child link="camera"/>
        <origin xyz="${camera_x} ${camera_y} ${camera_z}"/>
    </joint>
</robot>